#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Minesweeper Game.
usage: game [width] [height] [number of mines]
"""
import sys
import minesweeper
if __name__ == '__main__':
    minesweeper.play_game(*map(int, sys.argv[1:]))
